### ISSUE TITLE
Pop-up windows explaining how to use the site

### ISSUE THREAD

**Issue by joshwestbury** [danhagg/transport-app#42]
We may want to use bootstrap models for this: http://getbootstrap.com/docs/4.0/components/modal/

**Comment by danhagg** [comment]
About popup 1 (modal)
Loads on first visit and can be minimized

popup 2
markers appear for white n red flags violent non violent

**Comment by danhagg** [comment]
Safe Travels informs you of the local bus and bikeways in Houston as well as the local crime data to help you travel safely through the city.
* Click the "Get Walkscore" button to get a general feel for how walkable your current location is
* Click “Bus Routes” or “Bikeways” to view the local options for travel.
* Click "Crime Heat Map" for a general view of the latest crime activity.
* Click "Crime Details” to view details about individual crimes.
____________

SafeTravels visualizes local bus and bikeways in Houston as well as local crime data to help you navigate through the city safely. **Click the Map Menu button to get started.**

From here you can visualize Houston crime data as a heatmap or as individual markers that, when clicked, provide detailed information for particular crimes. The Map Menu also allows you to visualize bus and bike route information in order determine the safest route. 

Finally, from the Map, click the "Get WalkScore" button to see the walk, bike, and transit score for your location, in addition to nearby amenities, such as restaurants, entertainment, and groceries.    

Currently, SafeTravels only supports data for Houston, Texas, but we are working to include more cities soon.

**Comment by loragriffin** [comment]
completed
